- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.130.0.17
  tasks:
  - name: Change mongo config file
    become: true
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    tags: db-tag
    notify:
      - restart mongodb
  - name: Add unit file for Puma
    become: true
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    tags: app-tag
    notify: reload puma
  - name: Add config for db connection
    template:
      src: files/db_config.j2
      dest: /home/ubuntu/db_config
    tags: app-tag
  - name: enable puma
    become: true
    service:
      name: puma
      enabled: yes
    tags: app-tag

  - name: Install git
    apt:
      name: git
    become: true
    tags: deploy-tag
  - name: Clone repo
    git:
      repo: https://github.com/express42/reddit.git
      dest: /home/ubuntu/reddit
      version: monolith
    notify: reload puma
    tags: deploy-tag
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
    tags: deploy-tag

  handlers:
  - name: restart mongodb
    become: true
    service:
      name: mongod
      state: restarted
  - name: reload puma
    become: true
    service:
      name: puma
      state: restarted
